// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyhsfrumcxgwopqjptiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5aHNmcnVtY3hnd29wcWpwdGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjU3MDQsImV4cCI6MjA3MTQwMTcwNH0.j9wXcAr6s4o46eJ_PS-ERXB4HO9kESXVppLifM18638";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});